package com.example.Student_Library_Management_System.Service;


import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

    @Autowired
    StudentRepository studentRepository;

    public String createStudent(Student student){

        // student from the postman is already the basic attribute set


        //Card Should be autogenerated when createStudent function is called

        Card card = new Card();
        card.setCardStatus(CardStatus.ACTIVATED); // card status being saved
        card.setStudentVariableName(student); // Foreign key
        // Filling the value with the unidirectional part.


        //Let's go to the student
        student.setCard(card);

        //if there was a unidirectional mapping  :  we had to save both of them,
        // but  we are super advance and are using bidirectional mapping : child will automatically be saved.

        studentRepository.save(student);

        //By cascading effect , child will automatically be saved.

        return "Student card Added";
    }
}
